"use client";

import { useState } from "react";
import StatusBadge from "@/components/StatusBadge";
import ConfirmSubmitButton from "../../../../components/ConfirmSubmitButton";

type ContractItem = {
  id: string;
  templateName: string;
  versionNo: number;
  generatedBy: string | null;
  filePath: string | null;
  fileUrl: string | null;
  status: string;
  generatedAt: Date;
};

type ContractsSectionProps = {
  caseId: string;
  contracts: ContractItem[];
  onDeleteAction: (formData: FormData) => void;
};

export default function ContractsSection({
  caseId,
  contracts,
  onDeleteAction,
}: ContractsSectionProps) {
  const [expanded, setExpanded] = useState(false);

  const hasMore = contracts.length > 3;
  const visibleContracts = expanded ? contracts : contracts.slice(0, 3);

  return (
    <div
      id="contracts-section"
      className="rounded-2xl border border-white/10 bg-white/5 p-8 mb-8"
    >
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-2xl font-semibold">Contracts</h2>
        <p className="text-sm text-white/50">{contracts.length} contract(s)</p>
      </div>

      {contracts.length === 0 ? (
        <p className="text-white/60">No contracts yet.</p>
      ) : (
        <>
          <div className="space-y-4">
            {visibleContracts.map((contract) => (
              <div
                key={contract.id}
                className="rounded-xl border border-white/10 bg-black/30 p-4"
              >
                <div className="flex items-start justify-between gap-4 mb-4">
                  <div>
                    <p className="text-white/50 text-sm mb-1">Template Name</p>
                    <p className="font-medium break-all">
                      {contract.templateName}
                    </p>
                  </div>

                  <div className="shrink-0 flex gap-2">
                    {contract.fileUrl ? (
                      <a
                        href={contract.fileUrl}
                        target="_blank"
                        rel="noreferrer"
                        className="inline-block rounded-lg bg-white text-black px-4 py-2 font-medium"
                      >
                        Open
                      </a>
                    ) : (
                      <span className="inline-block rounded-lg border border-white/10 px-4 py-2 text-white/40">
                        No File
                      </span>
                    )}

                    <form action={onDeleteAction}>
                      <input type="hidden" name="caseId" value={caseId} />
                      <input
                        type="hidden"
                        name="contractId"
                        value={contract.id}
                      />

                      <ConfirmSubmitButton
                        label="Delete Contract"
                        confirmMessage="Are you sure you want to delete this contract?"
                        className="rounded-lg border border-red-500/30 px-4 py-2 text-red-300 hover:bg-red-500/10"
                      />
                    </form>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                  <div>
                    <p className="text-white/50 mb-1">Version</p>
                    <p>{contract.versionNo}</p>
                  </div>

                  <div>
                    <p className="text-white/50 mb-1">Status</p>
                    <StatusBadge value={contract.status} />
                  </div>

                  <div>
                    <p className="text-white/50 mb-1">Generated By</p>
                    <p>{contract.generatedBy ?? "-"}</p>
                  </div>

                  <div>
                    <p className="text-white/50 mb-1">Generated At</p>
                    <p>{new Date(contract.generatedAt).toLocaleString()}</p>
                  </div>
                </div>

                <div className="mt-4">
                  <p className="text-white/50 mb-1 text-sm">File URL</p>
                  {contract.fileUrl ? (
                    <p className="break-all">{contract.fileUrl}</p>
                  ) : (
                    <p>-</p>
                  )}
                </div>
              </div>
            ))}
          </div>

          {hasMore && (
            <div className="mt-6">
              <button
                type="button"
                onClick={() => setExpanded((prev) => !prev)}
                className="rounded-lg border border-white/10 px-4 py-2 text-white/80 hover:bg-white/10"
              >
                {expanded ? "Show Less" : `Show More (${contracts.length - 3})`}
              </button>
            </div>
          )}
        </>
      )}
    </div>
  );
}